name: SpinHeads
version: ${project.version}
author: Mas281

depend: [ActionUtil]
main: io.samdev.spinheads.SpinHeads
api-version: 1.14
load: POSTWORLD

commands:
  spinheads:
    aliases: [sh]